# Site wide configuration

title: Trust me, I'm a software engineer.
locale: en_US
description: "/* TODO: Add site description */"
logo: #site-logo.png
search: true
url: https://dkopecek.github.io

# Jekyll configuration

permalink:   /:categories/:title/
markdown:    kramdown
highlighter: pygments
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap

plugins:
  - jekyll-redirect-from

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..2
  use_coderay: false

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md", "vendor"]


# Site owner
owner:
  name: Daniel Kopeček
  avatar: bio-photo.jpg
  email: dkopecek@redhat.com
  disqus-shortname: dnkrh
  twitter: #username
  facebook: #username
  github: dkopecek
  stackexchange: #http://stackoverflow.com/users/123456/username
  linkedin: dkopecek
  instagram: #username
  flickr: #username
  tumblr: #username
  pinterest: #username
  google:
    plus: #username
    analytics:
    verify:
    ad-client:
    ad-slot: 
  bing-verify:
